version: '3'
services: 

  mutualssl:
    image: csp-nginx:1.0
    volumes:
      - /opt/csp/nginx/ssl:/etc/nginx/ssl
      - /opt/csp/nginx/csp-sites:/etc/nginx/csp-sites
      - /opt/csp/www:/var/www/csp
    ports:
      - "8443:443"
      - "8080:80"