version: '3'

services: 


  csp-jitsi:
    image: csp-jitsimeet:1.0
    container_name: csp-jitsi
    hostname: csp-jitsi
    dns:
      - 8.8.8.8
    env_file:
      - .env
    environment:
      - DOMAIN=${JITSI_DOMAIN}
      - STUN=stun.ekiga.net
      - BRIDGE_IP=${HOST_IP}
      - BRIDGE_TCP_PORT=4443
      - BRIDGE_UDP_PORT=10000
    ports:
      - 4443:4443
      - 10000:10000/udp
    expose:
      - 80
    volumes:
      - /opt/csp/logs_jitsi:/var/log/jitsi
    networks:
      default:
        aliases:
          - ${JITSI_DOMAIN}

      
  vcb-admin:
    image: csp-java8:1.0
    container_name: csp-vcb_admin
    domainname: ${LOCAL_DOMAIN}
    hostname: csp-vcb_admin
    env_file:
        - .env
    command: sh -c "sleep 10 && java -Xmx512m -Dspring.profiles.active=docker -jar server.jar"
    working_dir: /opt/csp
    volumes:
        - ./vcb-admin-3.6.0-SNAPSHOT-exec.jar:/opt/csp/server.jar
        - /opt/csp/logs/:/opt/csplogs
        - SSLDatavolume:/opt/ssl/
        - JitsiDataVolume:/opt/vcb/data
    expose:
        - 9300
        
        
  vcb-teleconf:
    image: csp-java8:1.0
    container_name: csp-vcb_teleconf
    domainname: ${LOCAL_DOMAIN}
    hostname: csp-vcb_teleconf
    env_file:
        - .env
    command: java -Xmx512m -Dspring.profiles.active=docker -jar server.jar
    working_dir: /opt/csp
    volumes:
        - ./vcb-teleconf-3.6.0-SNAPSHOT-exec.jar:/opt/csp/server.jar
        - /opt/csp/logs/:/opt/csplogs
        - JitsiDataVolume:/opt/vcb/data
    expose:
        - 9100
        
        
volumes:
    JitsiDataVolume:
      external: true
    SSLDatavolume:
        external: true
      
      
networks:
  default:
    external:
      name: ${LOCAL_DOMAIN}
