version: '3'

services:
    sa-cfg:
        image: csp-java8:1.0
        container_name: sa-csp-cfg
        hostname: sa-csp-cfg
        command: java -Xmx512m -Dspring.profiles.active=docker -jar server.jar
        working_dir: /opt/csp
        environment:
            - CFG_DOCR_PORT=19090
            - CFG_PATH_REPO=/opt/cfg/data
            - ENABLE_OAM=false
        volumes:
            - ./conf-server-3.6.0-SNAPSHOT-exec.jar:/opt/csp/server.jar
            - /opt/csp/logs/:/opt/csplogs
            - ./cfg/data:/opt/cfg/data
        ports:
            - 127.0.0.1:19090:19090

    sa-cfg-client:
        image: csp-docker-java8:1.0
        depends_on:
            - sa-cfg
        container_name: sa-csp-cfg-client
        hostname: sa-csp-cfg-client
        command: java -Xmx512m -jar server.jar
        working_dir: /opt/csp
        environment:
         - CONF_SERVER_HOST=sa-csp-cfg
         - CONF_SERVER_PORT=19090
         - CONF_SERVER_PROTOCOL=http
         - INSTALLATION_FORCED=true
         - SERVER_ADDRESS=0.0.0.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./conf-client-cspapp-3.6.0-SNAPSHOT.jar:/opt/csp/server.jar
            - ./cfg-client/data:/opt/cspinst/
            - /opt/csp/:/opt/csp/
        ports:
            - 127.0.0.1:18080:18080

