version: '3'
services:
  redis:
    image: csp-redis:1.0
    container_name: csp-redis
    domainname: ${LOCAL_DOMAIN}
    hostname: csp-redis
    env_file:
      - .env
    ports:
      - 6379
    volumes:
      - REDISDataVolume:/data
      - /opt/csp/logs:/var/log/redis

volumes:
    REDISDataVolume:
      external: true

networks:
  default:
    external:
      name: ${LOCAL_DOMAIN}

