version: '3'
services: 

  mutualssl:
    image: csp-apache:1.0
    volumes:
      - /opt/csp/apache2/ssl:/etc/apache2/ssl
      - /opt/csp/apache2/csp-sites:/etc/apache2/csp-sites
      - /opt/csp/www:/var/www/localhost/htdocs
    ports:
      - "8443:443"
      - "8080:80"