version: '3'

services:
    activemq:
        container_name: csp-activemq
        domainname: ${LOCAL_DOMAIN}
        hostname: csp-activemq
        image: csp-activemq:1.0.1
        env_file:
            - .env
        expose:
            - 8161
            - 61616
            - 61613
        volumes:
            - AMQDatavolume:/data/activemq
            - /opt/csp/logs_activemq/:/opt/activemq/logs
            - AMQConfigVolume:/opt/activemq/conf

volumes:
    AMQDatavolume:
        external: true
    AMQConfigVolume:
        external: true

networks:
  default:
    external:
      name: ${LOCAL_DOMAIN}
