swagger: '2.0'
info:
  description: >-
    Anonymization service accepts data from the Integration Layer (cspId,
    integrationDataType and dataObject), and returns the dataObject with
    anonymized the appropriate fields of the dataObject json string.
  version: 1.0.0
  title: Anonymization API
host: int.csp.org
basePath: /v2
tags:
  - name: anon
    description: Anonymize data
schemes:
  - http
  - https
paths:
  /anon:
    post:
      tags:
        - anon
      summary: post data to anonymize
      description: ''
      operationId: anonData
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: intAnonDataObj
          description: Integration data to anonymize
          required: true
          schema:
            $ref: '#/definitions/IndegrationAnonData'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Malformed Integration Data Structure
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
definitions:
  IndegrationAnonData:
    type: object
    properties:
      cspId:
        type: string
      dataType:
        $ref: '#/definitions/IntegrationDataType'
      dataObject:
        type: string
  DataParams:
    type: object
    properties:
      cspId:
        type: string
      applicationId:
        type: string
      recordId:
        type: string
      timestamp:
        type: string
        format: dateTime
  IntegrationDataType:
    type: string
    enum:
      - event
      - threat
      - incident
      - vulnerability
      - artefact
      - chat
      - file
      - contact
      - trustCircle
